# Generated by Django 5.2.7 on 2025-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='best_day',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
